substitutions:
  _BUCKET: gs://www.bcow.me

steps:
- name: python:latest
  entrypoint: sh
  args:
  - '-c'
  - |
    apt update && apt -y install imagemagick
    ./resize_post_images.sh
    pip install -r requirements.txt
    statik
- name: gcr.io/cloud-builders/gsutil
  args:
  - -m
  - rsync
  - -d
  - -r
  - public/
  - ${_BUCKET}
- name: gcr.io/cloud-builders/gsutil
  args:
  - -m
  - rsync
  - -r
  - static/
  - ${_BUCKET}

# eof
