project-name: Antti's ramblings on life, the universe and everything
base-path: /
context:
        static:
                site-title: Random stuff
        dynamic:
                all-authors: session.query(Author).all()
